rules:
# ────────────────────────────────────────────────────────────────
#  🚨 1. Блокирующая проверка (SSR F) — уже есть выше
# ────────────────────────────────────────────────────────────────
  - id: ssrf-node
    pattern-either:
      - pattern: axios("http://$URL")
      - pattern: fetch("http://$URL")
      - pattern: request.get($URL)
    message: "Возможен SSRF – пользователь формирует URL запроса"
    languages: [js, ts]
    severity: ERROR

# ────────────────────────────────────────────────────────────────
#  ℹ️ 2. Server‑Side Template Injection (Pug/EJS/Handlebars)
#       (только если template приходит из req/query/body)
# ────────────────────────────────────────────────────────────────
  - id: ssti-node
    pattern-either:
      # Pug
      - pattern: |
          const $tpl = $REQ.$_ ;
          pug.compile($tpl)($ANY*)
      # EJS
      - pattern: |
          const $tpl = $REQ.$_ ;
          ejs.render($tpl,$ANY*)
      # Handlebars
      - pattern: |
          const $tpl = $REQ.$_ ;
          handlebars.compile($tpl)($ANY*)
    message: "SSTI: компилируется шаблон, полученный от пользователя"
    languages: [js, ts]
    severity: INFO

# ────────────────────────────────────────────────────────────────
#  ℹ️ 3. DOM‑XSS (обновили — ловим прямую вставку во «взрывоопасные» API)
# ────────────────────────────────────────────────────────────────
  - id: dom-xss-assign
    patterns:
      - pattern: $EL.innerHTML = $USR
      - pattern-not: $EL.innerHTML = DOMPurify.sanitize($USR)
    message: "DOM‑XSS: присвоение innerHTML из непроверенных данных"
    languages: [js, ts]
    severity: INFO

# ────────────────────────────────────────────────────────────────
#  ℹ️ 4. NULL‑byte path trick (Node FS / path APIs)
#       ловим '\0' в пути, который пришёл от юзера
# ────────────────────────────────────────────────────────────────
  - id: null-byte-path
    pattern: |
      fs.$FUNC($PATH, ...)
    metavariable-pattern:
      metavariable: $PATH
      pattern: $REQ.$_
    pattern-either:
      - pattern-inside: |
          if ($PATH.includes("\0")) { ... }    # уже проверяют ↔ игнорируем
    pattern-not-inside: |
      if ($PATH.includes("\0")) { ... }
    message: "Null‑byte в пути из пользовательского ввода (обход проверок FS)"
    languages: [js, ts]
    severity: INFO

# ────────────────────────────────────────────────────────────────
#  ℹ️ 5. Broken Access Control: открытый /admin‑роут без middle‑ware
#       (нет verify/auth/check/token и есть только один обработчик)
# ────────────────────────────────────────────────────────────────
  - id: bac-open-admin-route
    patterns:
      - pattern: |
          app.get("/admin", $HANDLER)
      - pattern-not: |
          app.get("/admin", $AUTH, $HANDLER)
    message: "Broken Access Control: /admin доступен без проверки авторизации"
    languages: [js, ts]
    severity: INFO
