# .semgrep_rules.yml
rules:
  # ────────────────────────────────────────────────────────────────
  #  ❗ Оставляем ТОЛЬКО одну блокирующую проверку (пример – SSRF)
  # ────────────────────────────────────────────────────────────────
  - id: ssrf-node
    # самый простой пример паттерна (покрывает axios/fetch/request.get)
    pattern-either:
      - pattern: |
          axios("http://$URL")
      - pattern: |
          fetch("http://$URL")
      - pattern: |
          request.get($URL)
    message: "Возможен SSRF – пользователь формирует URL запроса"
    languages: [js, ts]
    severity: ERROR        # ← ломает build, пока не пофиксим

  # ────────────────────────────────────────────────────────────────
  #  ✅ Все остальные хотим видеть, но НЕ блокировать
  #     (меняем severity на INFO, WARNING и т.п.)
  # ────────────────────────────────────────────────────────────────
  - id: dom-xss-demo
    pattern: |
      document.write(...)
    message: "DOM‑XSS (демонстрационное правило)"
    languages: [js]
    severity: INFO         # ← билд НЕ упадёт
