rules:
# ───────────────────── 1. SSRF (ERROR) ─────────────────────
- id: ssrf-node
  languages: [js, ts]
  severity: ERROR
  pattern-either:
    - pattern: request.get($URL)
    - pattern: request.$FUNC($URL)
    - pattern: axios($URL, ...)
    - pattern: fetch($URL, ...)

# ─── 2. DOM‑XSS: присвоение innerHTML без санитайзера ───
- id: dom-xss-assign
  message: "DOM‑XSS: присвоение innerHTML из непроверенных данных"
  severity: INFO
  languages: [js, ts]

  patterns:
    # 1) опасное присвоение
    - pattern: |
        $EL.innerHTML = $DATA

    # 2) но НЕ триггерим, если данные проходят через DOMPurify
    - pattern-not-inside: |
        $EL.innerHTML = DOMPurify.sanitize(...)


# ─── 3. Null‑byte обход проверок путей (INFO) ──────────────
- id: null-byte-path
  message: "Null‑byte в пути из пользовательского ввода (обход проверок FS)"
  severity: INFO
  languages: [js, ts]
  patterns:
    # Любой вызов fs.* с path‑переменной
    - pattern-either:
        - pattern: fs.$FUNC($PATH, ...)
        - pattern: path.join(..., $PATH)
        - pattern: path.resolve(..., $PATH)
    # $PATH пришёл из запроса
    - metavariable-pattern:
        metavariable: $PATH
        pattern: $REQ.$_
    # нет проверки на ‘\0’
    - pattern-not-inside: |
        if ($PATH.includes("\0")) { ... }

# ─── 4. SSTI через eval / EJS (INFO) ───────────────────────
- id: ssti-node
  languages: [js, ts]
  severity: INFO
  pattern-either:
    - pattern: eval($ANY)
    - pattern: pug.compile($ANY)
    - pattern: ejs.render($ANY, ...)

# ─── 5. Open /admin без middleware (INFO) ──────────────────
# ─── 5. Broken‑Access‑Control: открытый /admin без middleware ───
# ──────────────────────────────────
# Broken Access Control (open /admin)
# ──────────────────────────────────
- id: bac-open-admin-route
  languages: [js, ts]
  severity: INFO
  pattern: app.get('/admin', $HANDLER)
  pattern-not: app.get('/admin', verify, ...)

