name: DevSecOps

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Pull Juice Shop
        run: docker pull bkimminich/juice-shop:latest

      - name: Run Juice Shop
        run: docker run -d -p 3000:3000 --name juice bkimminich/juice-shop:latest

      - uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'image'
          image-ref: bkimminich/juice-shop:latest
          ignore-unfixed: true
          vuln-type: 'os,library'

      - uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://localhost:3000'
          cmd_options: '-m 3 -I -j -J zap-report.json'

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            zap-report.json
            trivy-results.json
