name: DevSecOps
on: [push, pull_request, workflow_dispatch]

env:
  JUICE_TAG: latest
  TRIVY_SEVERITY: CRITICAL,HIGH

# ---------- 1. Secrets scan ----------
jobs:
  secrets:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: --timeout=10m

# ---------- 2. SAST: CodeQL + Semgrep ----------
  sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with: { languages: javascript }
      - uses: github/codeql-action/analyze@v3
      # - uses: returntocorp/semgrep-action@v1
      #   with:
      #     config: p/owasp-top-ten
      #     generateSarif: true
      #     output: semgrep.sarif
      - name: Run Semgrep
        id: semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/owasp-top-ten             # или .semgrep_rules.yml
          generateSarifReport: true                 # ← включаем SARIF
          output: semgrep.sarif               # имя файла на диске

      # ---------- загружаем SARIF как Code‑Scanning ----------
      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif

# ---------- 3. Runtime scans: Trivy + ZAP ----------
  runtime-scan:
    runs-on: ubuntu-latest
    services:
      juice:
        image: bkimminich/juice-shop:latest
        ports:
          - 3000:3000
    steps:
      - uses: actions/checkout@v4

      - name: Trivy image scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: bkimminich/juice-shop:latest
          scan-type: image
          vuln-type: 'os,library'
          severity: CRITICAL,HIGH
          format: json
          output: trivy-result.json
          exit-code: 0        

      - name: ZAP baseline scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: http://localhost:3000
          cmd_options: "-m 3 -I -j -J zap-report.json"  
          fail_action: true

      - name: SBOM (CycloneDX for image)
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $PWD:/out aquasec/trivy:0.51.2 \
            image --format cyclonedx -o /out/sbom.json bkimminich/juice-shop:latest

      - uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            trivy-result.json
            zap-report.json
            sbom.json
