name: DevSecOps
on: [push, pull_request, workflow_dispatch]

env:
  JUICE_TAG: latest
  TRIVY_SEVERITY: CRITICAL,HIGH

# ---------- 1. Secrets scan ----------
jobs:
  secrets:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: --timeout=10m

# ---------- 2. SAST: CodeQL + Semgrep ----------
  sast:
    runs-on: ubuntu-latest
    # needs: secrets
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with: { languages: javascript }
      - uses: github/codeql-action/analyze@v3
      - uses: returntocorp/semgrep-action@v1
        with:
          config: p/owasp-top-ten

# ---------- 3. Runtime scans: Trivy + ZAP ----------
  runtime-scan:
    runs-on: ubuntu-latest
    # needs: sast
    services:
      juice:
        image: bkimminich/juice-shop
        ports:
          - 3000:3000         # выражения тут запрещены, пишем константу
    steps:
      - uses: actions/checkout@v4

      # Trivy image scan с quality-gate
      - name: Trivy image scan
        uses: aquasecurity/trivy-action@0.19.0
        with:
          image-ref: bkimminich/juice-shop:${{ env.JUICE_TAG }}
          scan-type: image
          vuln-type: 'os,library'
          severity: ${{ env.TRIVY_SEVERITY }}
          format: json
          output: trivy-result.json
          exit-code: 1            # «красный» билд, если найдены High/Critical

      # ZAP Baseline DAST
      - name: ZAP baseline scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: http://localhost:3000
          cmd_options: "-t 100 -m 3 -I -j -J zap-report.json"
          fail_action: true       # билд упадёт, если алертов больше порога

      # SBOM (CycloneDX JSON)
      - name: SBOM
        run: |
          docker run --rm \
            -v $PWD:/sbom aquasecurity/trivy:0.51.2 \
            sbom --format cyclonedx --output sbom.json bkimminich/juice-shop:${{ env.JUICE_TAG }}

      # Отчёты
      - uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            trivy-result.json
            zap-report.json
            sbom.json
